# SPDX-FileCopyrightText: 2023 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

---
blank_issues_enabled: false
contact_links:
  - name: Community Discussions
    url: https://community.dataportal.se/
    about: For general community discussions about Open Source, Data and more.
    #  - name: Security Reports
    #url: todo, add when okd
    #about: Please read about our security policy here.
