---
# Configuration file for MegaLinter.
# See configuration options at https://oxsecurity.github.io/megalinter/configuration/ and more in each linter documentation.

# General
PRINT_ALPACA: false
APPLY_FIXES: all

DISABLE_ERRORS: false
SHOW_ELAPSED_TIME: true
SHOW_SKIPPED_LINTERS: false

# Reporter options
CLEAR_REPORT_FOLDER: true
EMAIL_REPORTER: false
TEXT_REPORTER: true
SARIF_REPORTER: true
GITHUB_COMMENT_REPORTER: false
GITHUB_STATUS_REPORTER: true
GITLAB_COMMENT_REPORTER: false
UPDATED_SOURCES_REPORTER: true

# Lint specifig settings
ENABLE_LINTERS:
  [
    MARKDOWN_MARKDOWNLINT,
    MARKDOWN_MARKDOWN_LINK_CHECK,
    YAML_PRETTIER,
    YAML_V8R,
    YAML_YAMLLINT,
    COPYPASTE_JSCPD,
    ACTION_ACTIONLINT,
    REPOSITORY_GITLEAKS,
  ]

COPYPASTE_JSCPD_ARGUMENTS: --ignore "LICENSE","**/report/**","megalinter-reports","LICENSES" --threshold "10"
